--[[
    GRF Editor [Version - 1.8.9.7]  [Build - 1.5.3.3063]
  
    This file was generated by GRF Editor
--______________________________________________________]]

-- Using GRF Editor Decompiler (beta 1.1.0)

SelectPackageItemData = {
	TabNameTbl = {
		[101060] = { [0] = "장비세트", [1] = "소모품 세트", [2] = "기타 세트" },
		[101062] = { [0] = "노비스 세트", [1] = "검사 세트" },
		[101470] = {
			[0] = "STR 감소 포션",
			[1] = "AGI 감소 포션",
			[2] = "VIT 감소 포션",
			[3] = "INT 감소 포션",
			[4] = "DEX 감소 포션",
			[5] = "LUK 감소 포션",
			[6] = "감소 포션 각각 1개씩"
		},
		[101471] = {
			[0] = "화염병",
			[1] = "염산병",
			[2] = "식인식물병",
			[3] = "코팅약",
			[4] = "기뢰병"
		},
		[101542] = {
			[0] = "이어링 쉐도우",
			[1] = "펜던트 쉐도우",
			[2] = "아머 쉐도우",
			[3] = "슈즈 쉐도우"
		},
		[101547] = {
			[0] = "이어링 쉐도우",
			[1] = "펜던트 쉐도우",
			[2] = "아머 쉐도우",
			[3] = "슈즈 쉐도우"
		},
		[101552] = { [0] = "웨폰 쉐도우", [1] = "쉴드 쉐도우" },
		[101555] = { [0] = "웨폰 쉐도우", [1] = "쉴드 쉐도우" },
		[101563] = {
			[0] = "이그니스 캡",
			[1] = "팬텀 캡",
			[2] = "스트라이프 햇",
			[3] = "레드 클락 카스켓",
			[4] = "대마도사의 예관",
			[5] = "천헐궁 하늘의 보관",
			[6] = "인마궁 하늘의 보관"
		},
		[101565] = {
			[0] = "클래스 쉐도우 마법서(물리)",
			[1] = "클래스 쉐도우 마법서(마법)",
			[2] = "스킬 쉐도우 마법서(물리)",
			[3] = "스킬 쉐도우 마법서(마법)"
		},
		[101423] = {
			[0] = "어태커 부스터 세트",
			[1] = "레인지 부스터 세트",
			[2] = "엘리멘탈 부스터 세트",
			[3] = "디펀트 부스터 세트"
		},
		[101454] = {
			[0] = "+7 메탈 투핸드소드",
			[1] = "+7 메탈 랜스",
			[2] = "+7 메탈 메이스",
			[3] = "+7 메탈 투핸드액스",
			[4] = "+7 메탈 대거",
			[5] = "+7 메탈 북",
			[6] = "+7 메탈 스태프",
			[7] = "+7 메탈 카타르",
			[8] = "+7 메탈 보우",
			[9] = "+7 메탈 리볼버",
			[10] = "+7 메탈 강아지풀"
		},
		[101456] = {
			[0] = "부스터 가면 A타입",
			[1] = "부스터 가면 B타입",
			[2] = "부스터 가면 C타입"
		},
		[101457] = {
			[0] = "부스터 스카프 A타입",
			[1] = "부스터 스카프 B타입",
			[2] = "부스터 스카프 C타입"
		},
		[101458] = {
			[0] = "의상 초보자 토끼 후드",
			[1] = "의상 검은 고양이 후드",
			[2] = "의상 초보자 다람쥐 귀 모자",
			[3] = "의상 초보자 검은 달고양이"
		},
		[101459] = {
			[0] = "의상 초보자 빨간 책가방",
			[1] = "의상 초보자 검정 책가방",
			[2] = "의상 초보자 파란 책가방",
			[3] = "의상 초보자 보라 책가방"
		},
		[101453] = {
			[0] = "코르 코어&의문의 부속품",
			[1] = "바르밀 티켓",
			[2] = "자수정 조각",
			[3] = "설화의 꽃잎"
		},
		[101654] = { [0] = "이어링 쉐도우", [1] = "펜던트 쉐도우" },
		[101657] = {
			[0] = "이어링 쉐도우",
			[1] = "펜던트 쉐도우",
			[2] = "슈즈 쉐도우",
			[3] = "아머 쉐도우"
		},
		[101662] = { [0] = "웨폰 쉐도우", [1] = "아머 쉐도우" },
		[101727] = {
			[0] = "이어링 쉐도우",
			[1] = "펜던트 쉐도우",
			[2] = "아머 쉐도우",
			[3] = "슈즈 쉐도우"
		},
		[101728] = {
			[0] = "이어링 쉐도우",
			[1] = "펜던트 쉐도우",
			[2] = "아머 쉐도우",
			[3] = "슈즈 쉐도우"
		},
		[101729] = { [0] = "웨폰 쉐도우", [1] = "쉴드 쉐도우" },
		[101801] = {
			[0] = "이어링 쉐도우",
			[1] = "펜던트 쉐도우",
			[2] = "아머 쉐도우",
			[3] = "슈즈 쉐도우"
		},
		[101806] = { [0] = "웨폰 쉐도우", [1] = "쉴드 쉐도우" },
		[101856] = {
			[0] = "이어링 쉐도우",
			[1] = "펜던트 쉐도우",
			[2] = "아머 쉐도우",
			[3] = "슈즈 쉐도우"
		},
		[101862] = { [0] = "웨폰 쉐도우", [1] = "쉴드 쉐도우" },
		[101919] = { [0] = "웨폰 쉐도우", [1] = "쉴드 쉐도우" },
		[101922] = { [0] = "웨폰 쉐도우", [1] = "쉴드 쉐도우" },
		[102084] = {
			[0] = "그레네이드런처",
			[1] = "리볼버",
			[2] = "개틀링건",
			[3] = "샷건",
			[4] = "라이플"
		},
		[102213] = {
			[0] = "개조 상자 I",
			[1] = "개조 상자 II",
			[2] = "개조 상자 III",
			[3] = "개조 상자 IV",
			[4] = "개조 상자 V",
			[5] = "개조 상자 VI"
		},
		[102214] = {
			[0] = "제련망치 I",
			[1] = "제련망치 II",
			[2] = "제련망치 III",
			[3] = "제련망치 IV",
			[4] = "제련망치 V",
			[5] = "제련망치 VI"
		},
		[102215] = {
			[0] = "생체연구소 무기",
			[1] = "전사자의 투구",
			[2] = "게펜 마법 대회"
		},
		[102216] = {
			[0] = "생체연구소 투구",
			[1] = "시간의 서클릿",
			[2] = "오토매틱 방어구",
			[3] = "레이싱캡",
			[4] = "OS무기",
			[5] = "시간의방어구"
		},
		[102217] = {
			[0] = "왕가의 활",
			[1] = "쉐도우 스태프",
			[2] = "아이언 네일",
			[3] = "블루 크리스탈 스태프",
			[4] = "냉기의 지팡이",
			[5] = "고대 영웅의 부츠"
		},
		[102218] = {
			[0] = "홍련의 검",
			[1] = "아이언 스태프",
			[2] = "동방의 보검",
			[3] = "키리노츠유",
			[4] = "스루도이카제",
			[5] = "풍마수리검 청명"
		},
		[102219] = {
			[0] = "나르시스 보우",
			[1] = "마도검",
			[2] = "복수자",
			[3] = "아쿠아틱 스피어",
			[4] = "퇴마의 성서",
			[5] = "전율의 카타르"
		},
		[102220] = {
			[0] = "일천일양",
			[1] = "혼령추",
			[2] = "냥냥 강아지풀",
			[3] = "프리덤 스틱",
			[4] = "블레스드 나이프"
		},
		[102221] = {
			[0] = "드래고닉 슬레이어",
			[1] = "라이트 블레이드",
			[2] = "슬레이트 소드",
			[3] = "소라고둥 나팔",
			[4] = "가시철사 채찍",
			[5] = "메테오 스트라이커"
		},
		[102222] = {
			[0] = "세인트 홀",
			[1] = "레이 너클",
			[2] = "블레이드 카타르",
			[3] = "페이탈리스트",
			[4] = "스칼렛 드래곤 레더보우"
		},
		[102223] = {
			[0] = "크림슨 로즈",
			[1] = "마스터 소울 라이플",
			[2] = "데몬 슬레이어 샷",
			[3] = "골든 로드 런처",
			[4] = "더 블랙"
		},
		[102306] = {
			[0] = "의상 롭이어 래빗 망토",
			[1] = "의상 하트쉬폰 래빗",
			[2] = "의상 이상한 나라의 티 파티",
			[3] = "의상 쇼콜라 래빗 헤어"
		},
		[102338] = {
			[0] = "의상 음표 헤드폰",
			[1] = "의상 음악의 장식",
			[2] = "의상 휘파람"
		},
		[102467] = {
			[0] = "의상 오션 컬러 롱",
			[1] = "의상 아쿠아의 지느러미 장식",
			[2] = "의상 세일러 캡"
		},
		[102631] = {
			[0] = "하늘을 나는 시나모롤",
			[1] = "시나모롤",
			[2] = "시나모롤 가방",
			[3] = "왕관 시나모롤 가방"
		},
		[102732] = {
			[0] = "이스가르드 워리어 크라운",
			[1] = "이스가르드 매지션 크라운",
			[2] = "이스가르드 레인저 크라운"
		},
		[102733] = {
			[0] = "입에 문 하트 에이스",
			[1] = "입에 문 스페이드 에이스",
			[2] = "입에 문 다이아몬드 에이스",
			[3] = "입에 문 클로버 에이스"
		},
		[102734] = {
			[0] = "로키의 동전",
			[1] = "로키의 하얀색 동전",
			[2] = "로키의 검정색 동전",
			[3] = "로키의 황금색 동전"
		},
		[102735] = {
			[0] = "로키의 조언(근접물리)",
			[1] = "로키의 조언(마법)",
			[2] = "로키의 조언(원거리물리)",
			[3] = "로키의 조언(방어)"
		},
		[102771] = {
			[0] = "의상 스노우맨 모자",
			[1] = "의상 겨울밤의 종소리",
			[2] = "의상 산타 테디베어 인형 가방"
		},
		[102812] = { [0] = "이어링 쉐도우", [1] = "펜던트 쉐도우" },
		[102949] = { [0] = "의상 슈퍼 소닉 미니미", [1] = "의상 카오스 에메랄드" },
		[103260] = { [0] = "골드 피오니아", [1] = "레드 피오니아" },
		[103261] = { [0] = "둥실둥실 파라솔", [1] = "둥실둥실 빨간 파라솔" },
		[103262] = { [0] = "블루 선베드", [1] = "그린 선베드" },
		[103263] = { [0] = "보라별 발자국", [1] = "노란별 발자국" },
		[103094] = {
			[0] = "의상 늘어진 페이차이",
			[1] = "의상 산책이 즐거운 아지",
			[2] = "의상 게으른 고양이 루커",
			[3] = "의상 행운을 부르는 타이즈"
		},
		[103318] = { [0] = "농축 에르늄", [1] = "농축 오리데오콘" },
		[103319] = { [0] = "고농축 에르늄", [1] = "고농축 오리데오콘" },
		[103597] = {
			[0] = "딸기 왕자의 왕관",
			[1] = "로키 & 니드호그의 모자",
			[2] = "피린트 스카프"
		},
		[103903] = {
			[0] = "의상 용의 전사 모자",
			[1] = "의상 용의 전사 망토와 지팡이"
		},
		[103904] = {
			[0] = "의상 늘어진 시푸 인형",
			[1] = "의상 늘어진 타이그리스 인형"
		},
		[103905] = { [0] = "의상 수묵화(낮)", [1] = "의상 수묵화(밤)" },
		[103906] = { [0] = "팬더 발자국(걸칠것)", [1] = "팬더 칼라 발자국(걸칠것)" },
		[103898] = { [0] = "의상 사자의 인도자 투구", [1] = "의상 우제트" },
		[103899] = { [0] = "의상 심판의 천칭", [1] = "의상 천칭 날개" },
		[103900] = { [0] = "의상 수호자의 문자", [1] = "의상 인도자의 문자" },
		[104714] = {
			[0] = "의상 투슬리스 인형탈",
			[1] = "의상 미니 투슬리스",
			[2] = "의상 투슬리스 후드"
		},
		[104715] = {
			[0] = "의상 투슬리스 날개",
			[1] = "투슬리스 발자국(걸칠것)",
			[2] = "튀어 오르는 투슬리스 발자국(걸칠것)"
		},
		[104716] = { [0] = "의상 높은 구름 위", [1] = "의상 구름 위 오로라" },
		[105356] = {
			[0] = "의상 페탈 후드",
			[1] = "의상 무카 솜브레로",
			[2] = "의상 카피바라"
		},
		[105526] = { [0] = "의상 리아멧트의 머리띠", [1] = "의상 체인드 베어" },
		[105527] = {
			[0] = "의상 악몽의 피아멧트 보닛",
			[1] = "의상 피아멧트 롤 헤어롱"
		},
		[105528] = { [0] = "의상 나이트메어 체인", [1] = "의상 악몽의 매드바니" },
		[105830] = {
			[0] = "그레네이드런처",
			[1] = "리볼버",
			[2] = "개틀링건",
			[3] = "샷건",
			[4] = "라이플"
		},
		[105831] = {
			[0] = "그레네이드런처",
			[1] = "리볼버",
			[2] = "개틀링건",
			[3] = "샷건",
			[4] = "라이플"
		},
		[105927] = { [0] = "백여우 후드트윈", [1] = "백여우 후드트윈(장식없음)" },
		[105928] = { [0] = "날개달린 트윈헤어", [1] = "날개달린 브론드헤어" },
		[105929] = { [0] = "원더풀 롱", [1] = "원더풀 롱(장식없음)" }
	},
	PackageTbl = {
		[101060] = {
			[0] = {
				[0] = { item = 28144, cnt = 1, hour = 0, refine = 7, randomOption = true, grade = 1, type = 9 },
				[1] = { item = 600039, cnt = 1, hour = 0, refine = 5, randomOption = true, grade = 2, type = 9 },
				[2] = { item = 610052, cnt = 1, hour = 0, refine = 3, randomOption = true, grade = 3, type = 9 },
				[3] = { item = 630025, cnt = 1, hour = 24, refine = 0, randomOption = true, grade = 4, type = 9 }
			},
			[1] = {
				[0] = { item = 640045, cnt = 1, hour = 0, refine = 0, randomOption = true, grade = 1, type = 9 },
				[1] = { item = 650039, cnt = 1, hour = 0, refine = 0, randomOption = true, grade = 2, type = 9 },
				[2] = { item = 700074, cnt = 1, hour = 0, refine = 0, randomOption = true, grade = 3, type = 8 },
				[3] = { item = 800033, cnt = 1, hour = 0, refine = 0, randomOption = true, grade = 4, type = 15 }
			},
			[2] = {
				[0] = { item = 810033, cnt = 1, hour = 3, refine = 0, randomOption = false, grade = 1, type = 15 },
				[1] = { item = 820027, cnt = 1, hour = 5, refine = 0, randomOption = false, grade = 2, type = 15 },
				[2] = { item = 500071, cnt = 1, hour = 7, refine = 0, randomOption = false, grade = 3, type = 5 },
				[3] = { item = 510100, cnt = 1, hour = 9, refine = 0, randomOption = false, grade = 4, type = 5 },
				[4] = { item = 743, cnt = 2, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			}
		},
		[101062] = {
			[0] = {
				[0] = { item = 400360, cnt = 1, hour = 0, refine = 1, randomOption = true, grade = 1, type = 4 },
				[1] = { item = 410209, cnt = 1, hour = 0, refine = 3, randomOption = true, grade = 2, type = 4 },
				[2] = { item = 420179, cnt = 1, hour = 0, refine = 5, randomOption = false, grade = 3, type = 4 },
				[3] = { item = 450250, cnt = 1, hour = 0, refine = 7, randomOption = true, grade = 4, type = 4 }
			},
			[1] = {
				[0] = { item = 460049, cnt = 1, hour = 0, refine = 9, randomOption = true, grade = 1, type = 4 },
				[1] = { item = 470179, cnt = 1, hour = 0, refine = 12, randomOption = true, grade = 2, type = 4 },
				[2] = { item = 480250, cnt = 1, hour = 0, refine = 15, randomOption = false, grade = 3, type = 4 },
				[3] = { item = 490287, cnt = 1, hour = 0, refine = 20, randomOption = false, grade = 4, type = 4 }
			}
		},
		[101470] = {
			[0] = {
				[0] = { item = 22702, cnt = 6, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 22703, cnt = 6, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 22704, cnt = 6, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 22705, cnt = 6, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[4] = {
				[0] = { item = 22706, cnt = 6, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[5] = {
				[0] = { item = 22707, cnt = 6, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[6] = {
				[0] = { item = 22702, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 },
				[1] = { item = 22703, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 },
				[2] = { item = 22704, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 },
				[3] = { item = 22705, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 },
				[4] = { item = 22706, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 },
				[5] = { item = 22707, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101471] = {
			[0] = {
				[0] = { item = 7135, cnt = 50, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[1] = {
				[0] = { item = 7136, cnt = 50, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[2] = {
				[0] = { item = 7137, cnt = 50, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[3] = {
				[0] = { item = 7139, cnt = 50, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[4] = {
				[0] = { item = 7138, cnt = 50, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			}
		},
		[101542] = {
			[0] = {
				[0] = { item = 101543, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101544, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 101545, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 101546, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101547] = {
			[0] = {
				[0] = { item = 101548, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101549, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 101550, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 101551, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101552] = {
			[0] = {
				[0] = { item = 101553, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101554, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101555] = {
			[0] = {
				[0] = { item = 101556, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101557, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101563] = {
			[0] = {
				[0] = { item = 400022, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 400044, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 400049, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[3] = {
				[0] = { item = 400021, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[4] = {
				[0] = { item = 400054, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[5] = {
				[0] = { item = 400059, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[6] = {
				[0] = { item = 400061, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[101565] = {
			[0] = {
				[0] = { item = 100205, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 100206, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 100207, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 100208, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101423] = {
			[0] = {
				[0] = { item = 450001, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 480000, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[2] = { item = 470000, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[3] = { item = 490004, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[4] = { item = 100043, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 450004, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 480003, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[2] = { item = 470003, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[3] = { item = 490007, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[4] = { item = 100043, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 450002, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 480001, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[2] = { item = 470001, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[3] = { item = 490005, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[4] = { item = 100043, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 450003, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 480002, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[2] = { item = 470002, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[3] = { item = 490006, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[4] = { item = 100043, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101454] = {
			[0] = {
				[0] = { item = 21005, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 9 }
			},
			[1] = { [0] = { item = 1493, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 9 } },
			[2] = {
				[0] = { item = 16023, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 5 }
			},
			[3] = { [0] = { item = 1398, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 9 } },
			[4] = {
				[0] = { item = 13079, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 5 }
			},
			[5] = { [0] = { item = 1588, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 5 } },
			[6] = { [0] = { item = 2018, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 9 } },
			[7] = { [0] = { item = 1296, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 9 } },
			[8] = {
				[0] = { item = 18116, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 8 }
			},
			[9] = {
				[0] = { item = 13125, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 15 }
			},
			[10] = {
				[0] = { item = 26111, cnt = 1, hour = 0, refine = 7, randomOption = false, grade = 0, type = 5 }
			}
		},
		[101456] = {
			[0] = {
				[0] = { item = 410018, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 410019, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 410020, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[101457] = {
			[0] = {
				[0] = { item = 420153, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420154, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 420155, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[101458] = {
			[0] = {
				[0] = { item = 440003, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 14 }
			},
			[1] = {
				[0] = { item = 440006, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 14 }
			},
			[2] = {
				[0] = { item = 440007, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 14 }
			},
			[3] = {
				[0] = { item = 440009, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 14 }
			}
		},
		[101459] = {
			[0] = {
				[0] = { item = 20595, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 20575, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 20615, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[3] = {
				[0] = { item = 20616, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[101453] = {
			[0] = {
				[0] = { item = 25723, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 },
				[1] = { item = 25669, cnt = 18, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[1] = {
				[0] = { item = 1000103, cnt = 20, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[2] = {
				[0] = { item = 1000405, cnt = 20, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[3] = {
				[0] = { item = 1000608, cnt = 20, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			}
		},
		[101654] = {
			[0] = {
				[0] = { item = 101655, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101656, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101657] = {
			[0] = {
				[0] = { item = 101658, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101659, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 101660, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 101661, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101662] = {
			[0] = {
				[0] = { item = 101663, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101664, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101727] = {
			[0] = {
				[0] = { item = 101717, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101718, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 101719, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 101720, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101728] = {
			[0] = {
				[0] = { item = 101721, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101722, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 101723, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 101724, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101729] = {
			[0] = {
				[0] = { item = 101725, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101726, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101801] = {
			[0] = {
				[0] = { item = 101802, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101803, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 101804, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 101805, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101806] = {
			[0] = {
				[0] = { item = 101807, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101808, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101856] = {
			[0] = {
				[0] = { item = 101858, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101859, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 101860, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 101861, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101862] = {
			[0] = {
				[0] = { item = 101863, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101864, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101919] = {
			[0] = {
				[0] = { item = 101920, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101921, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[101922] = {
			[0] = {
				[0] = { item = 101923, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 101924, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[102084] = {
			[0] = {
				[0] = { item = 400391, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 400392, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 400393, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[3] = {
				[0] = { item = 400394, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[4] = {
				[0] = { item = 400395, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[102213] = {
			[0] = {
				[0] = { item = 100819, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 100820, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 100834, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 100918, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[4] = {
				[0] = { item = 100939, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[5] = {
				[0] = { item = 101190, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[102214] = {
			[0] = {
				[0] = { item = 100821, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 100822, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 100835, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 100917, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[4] = {
				[0] = { item = 100938, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[5] = {
				[0] = { item = 101189, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[102215] = {
			[0] = {
				[0] = { item = 100355, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 100270, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 100269, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[102216] = {
			[0] = {
				[0] = { item = 100684, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 100436, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 100354, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 100322, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[4] = {
				[0] = { item = 100321, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[5] = {
				[0] = { item = 100268, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[102217] = {
			[0] = {
				[0] = { item = 18164, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 8 }
			},
			[1] = {
				[0] = { item = 26118, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[2] = {
				[0] = { item = 1847, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[3] = {
				[0] = { item = 640004, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 9 }
			},
			[4] = {
				[0] = { item = 550007, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[5] = {
				[0] = { item = 22171, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 4 }
			}
		},
		[102218] = {
			[0] = {
				[0] = { item = 13485, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[1] = {
				[0] = { item = 2048, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 9 }
			},
			[2] = {
				[0] = { item = 21038, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 9 }
			},
			[3] = {
				[0] = { item = 28764, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[4] = {
				[0] = { item = 28763, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[5] = {
				[0] = { item = 13345, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 9 }
			}
		},
		[102219] = {
			[0] = {
				[0] = { item = 18170, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 8 }
			},
			[1] = {
				[0] = { item = 28744, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[2] = {
				[0] = { item = 28130, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 9 }
			},
			[3] = {
				[0] = { item = 32018, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[4] = {
				[0] = { item = 28630, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[5] = {
				[0] = { item = 28039, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 9 }
			}
		},
		[102220] = {
			[0] = {
				[0] = { item = 28631, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[1] = {
				[0] = { item = 26154, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[2] = {
				[0] = { item = 26155, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[3] = {
				[0] = { item = 550080, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[4] = {
				[0] = { item = 510070, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			}
		},
		[102221] = {
			[0] = {
				[0] = { item = 600004, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 9 }
			},
			[1] = {
				[0] = { item = 500003, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[2] = {
				[0] = { item = 500004, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[3] = {
				[0] = { item = 570002, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[4] = {
				[0] = { item = 580002, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[5] = {
				[0] = { item = 590002, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			}
		},
		[102222] = {
			[0] = {
				[0] = { item = 590003, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[1] = {
				[0] = { item = 560002, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[2] = {
				[0] = { item = 610003, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 9 }
			},
			[3] = {
				[0] = { item = 510006, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 5 }
			},
			[4] = {
				[0] = { item = 700003, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 8 }
			}
		},
		[102223] = {
			[0] = {
				[0] = { item = 32302, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 15 }
			},
			[1] = {
				[0] = { item = 28255, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 15 }
			},
			[2] = {
				[0] = { item = 28256, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 15 }
			},
			[3] = {
				[0] = { item = 28257, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 15 }
			},
			[4] = {
				[0] = { item = 28258, cnt = 1, hour = 0, refine = 11, randomOption = false, grade = 0, type = 15 }
			}
		},
		[102306] = {
			[0] = {
				[0] = { item = 480297, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 102193, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 400432, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 102193, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 410231, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 102193, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 420208, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 102193, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[102338] = {
			[0] = {
				[0] = { item = 19612, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 11 }
			},
			[1] = {
				[0] = { item = 19871, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 20492, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[102467] = {
			[0] = {
				[0] = { item = 420224, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 102441, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 480320, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 102441, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 400462, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 102441, cnt = 3, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[102631] = {
			[0] = {
				[0] = { item = 410268, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 410267, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 480243, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[3] = {
				[0] = { item = 480244, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[102732] = {
			[0] = {
				[0] = { item = 400105, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 400106, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 400107, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[102733] = {
			[0] = {
				[0] = { item = 420210, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420213, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 420220, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[3] = {
				[0] = { item = 420269, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[102734] = {
			[0] = {
				[0] = { item = 102278, cnt = 10, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 100487, cnt = 10, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 102343, cnt = 10, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 102676, cnt = 10, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[102735] = {
			[0] = {
				[0] = { item = 102277, cnt = 10, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 100488, cnt = 10, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 102342, cnt = 10, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[3] = {
				[0] = { item = 102677, cnt = 10, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[102771] = {
			[0] = {
				[0] = { item = 400585, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 410295, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 480405, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[102812] = {
			[0] = {
				[0] = { item = 24339, cnt = 1, hour = 0, refine = 10, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 24340, cnt = 1, hour = 0, refine = 10, randomOption = false, grade = 0, type = 4 }
			}
		},
		[102949] = {
			[0] = {
				[0] = { item = 410263, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420303, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103260] = {
			[0] = {
				[0] = { item = 400692, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 400693, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103261] = {
			[0] = {
				[0] = { item = 410351, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 410352, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103262] = {
			[0] = {
				[0] = { item = 420349, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420350, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103263] = {
			[0] = {
				[0] = { item = 1001617, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 },
				[1] = { item = 480470, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 1001650, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 },
				[1] = { item = 480470, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103094] = {
			[0] = {
				[0] = { item = 400664, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 410326, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 420338, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[3] = {
				[0] = { item = 480445, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103318] = {
			[0] = {
				[0] = { item = 7619, cnt = 100, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[1] = {
				[0] = { item = 7620, cnt = 100, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			}
		},
		[103319] = {
			[0] = {
				[0] = { item = 6241, cnt = 26, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[1] = {
				[0] = { item = 6240, cnt = 26, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			}
		},
		[103597] = {
			[0] = {
				[0] = { item = 20452, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 20212, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 20032, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103903] = {
			[0] = {
				[0] = { item = 400745, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 480517, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103904] = {
			[0] = {
				[0] = { item = 400747, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 400746, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103905] = {
			[0] = {
				[0] = { item = 420423, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420424, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103906] = {
			[0] = {
				[0] = { item = 1001908, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[1] = {
				[0] = { item = 1001909, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			}
		},
		[103898] = {
			[0] = {
				[0] = { item = 400749, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 400760, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103899] = {
			[0] = {
				[0] = { item = 410385, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 480523, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[103900] = {
			[0] = {
				[0] = { item = 420430, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420429, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[104714] = {
			[0] = {
				[0] = { item = 410440, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 400913, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[2] = {
				[0] = { item = 480596, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[104715] = {
			[0] = {
				[0] = { item = 480595, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 1002239, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			},
			[2] = {
				[0] = { item = 1002240, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 3 }
			}
		},
		[104716] = {
			[0] = {
				[0] = { item = 420511, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420512, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[105356] = {
			[0] = {
				[0] = { item = 400919, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 105059, cnt = 5, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[1] = {
				[0] = { item = 400803, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 105059, cnt = 5, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			},
			[2] = {
				[0] = { item = 410399, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 },
				[1] = { item = 105059, cnt = 5, hour = 0, refine = 0, randomOption = false, grade = 0, type = 2 }
			}
		},
		[105526] = {
			[0] = {
				[0] = { item = 401000, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 410474, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[105527] = {
			[0] = {
				[0] = { item = 401001, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420575, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[105528] = {
			[0] = {
				[0] = { item = 420576, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 480632, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[105830] = {
			[0] = {
				[0] = { item = 400391, cnt = 1, hour = 0, refine = 12, randomOption = false, grade = 4, type = 4 }
			},
			[1] = {
				[0] = { item = 400392, cnt = 1, hour = 0, refine = 12, randomOption = false, grade = 4, type = 4 }
			},
			[2] = {
				[0] = { item = 400393, cnt = 1, hour = 0, refine = 12, randomOption = false, grade = 4, type = 4 }
			},
			[3] = {
				[0] = { item = 400394, cnt = 1, hour = 0, refine = 12, randomOption = false, grade = 4, type = 4 }
			},
			[4] = {
				[0] = { item = 400395, cnt = 1, hour = 0, refine = 12, randomOption = false, grade = 4, type = 4 }
			}
		},
		[105831] = {
			[0] = {
				[0] = { item = 400391, cnt = 1, hour = 0, refine = 10, randomOption = false, grade = 2, type = 4 }
			},
			[1] = {
				[0] = { item = 400392, cnt = 1, hour = 0, refine = 10, randomOption = false, grade = 2, type = 4 }
			},
			[2] = {
				[0] = { item = 400393, cnt = 1, hour = 0, refine = 10, randomOption = false, grade = 2, type = 4 }
			},
			[3] = {
				[0] = { item = 400394, cnt = 1, hour = 0, refine = 10, randomOption = false, grade = 2, type = 4 }
			},
			[4] = {
				[0] = { item = 400395, cnt = 1, hour = 0, refine = 10, randomOption = false, grade = 2, type = 4 }
			}
		},
		[105927] = {
			[0] = {
				[0] = { item = 400757, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420426, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[105928] = {
			[0] = {
				[0] = { item = 420570, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420571, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		},
		[105929] = {
			[0] = {
				[0] = { item = 420515, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			},
			[1] = {
				[0] = { item = 420514, cnt = 1, hour = 0, refine = 0, randomOption = false, grade = 0, type = 4 }
			}
		}
	}
}

-- Function #0
LoadTable = function()
	for packageID, tabInfo in pairs(SelectPackageItemData.PackageTbl) do
		for tabID, itemList in pairs(tabInfo) do
			local tabName = ""
			if SelectPackageItemData.TabNameTbl[packageID] ~= nil and SelectPackageItemData.TabNameTbl[packageID][tabID] ~= nil then
				tabName = SelectPackageItemData.TabNameTbl[packageID][tabID]
			end
			result, msg = AddTab(packageID, tabID, tabName, #itemList + 1)
			if not(result) then
				return false, msg
			end
			for index, item in pairs(itemList) do
				result, msg = AddItem(packageID, tabID, index, item.item, item.cnt, item.hour, item.refine, item.randomOption, item.grade, item.type)
				if not(result) then
					return false, msg
				end
			end
		end
	end
	return true, "good"
end
