--[[
    GRF Editor [Version - 1.8.9.7]  [Build - 1.5.3.3063]
  
    This file was generated by GRF Editor
--______________________________________________________]]

-- Using GRF Editor Decompiler (beta 1.1.0)

SetupMSG = {
	Device = "使用硬件 T&L 加速弁遄COn Off f",
	Mode = "设置游戏分辨率",
	FullScreen = "使用全屏。On Off",
	MouseExclusive = "将鼠标移动区域限制在屏幕内。On Off",
	Sprite = "游戏内背景分辨率调整",
	Texture = "游戏内质感分辨率调整",
	Bgm_Volume = "调整背景音乐音量",
	Effect_Volume = "调整音效音量",
	bgm = "背景音乐。ON OFF",
	sound = "音效。On Off",
	battlemode = "点击Q ~ O 即可使用技能快捷栏2的技能",
	notrade = "自动拒绝交易申请。On Off",
	noshift = "不按Shift键以治愈来攻击敌人。On Off",
	noctrl = "不按Ctrl键来自动攻击。On Off",
	skillfail = "不显示红字的使用技能失败讯息。On Off",
	notalkmsg = "聊天内容不显示于聊天窗口上。On Off",
	notalkmsg2 = "聊天内容不显示于聊天窗口上(含公会内容)。 On Off",
	showname = "更改名称显示方式",
	fog = "开或关FOG特效。On Off",
	aura = "简化极光。On Off",
	window = "移动窗口位置时，会有吸附于其他窗口的属性。On Off",
	miss = "显示Miss。On Off",
	q1 = "用鼠标右键来使用存于F9的技能。On Off",
	q2 = "上、下转动鼠标滚轮来使用存于F7和F8的技能。On Off",
	effect = "特效 On Off",
	loginout = "显示公会成员和好友的登录相关信息。On Off",
	shopping = "点击一次来开启商店，点击商店名称右边则关闭商店。On Off",
	stateinfo = "显示有关状态图标的说明。On Off",
	snap = "在攻击对象附近引导鼠标光标。ON OFF",
	itemsnap = "在道具附近引导鼠标光标。ON OFF",
	skillsnap = "在技能施放的对象附近引导鼠标光标。ON OFF",
	hoai = "使用生命体的用户人工智能。ON OFF",
	merai = "使用佣兵的用户人工智能。 ON OFF",
	camera = "固定视角。ON OFF",
	lightmap = "在地图上显示阴影部分。On Off",
	ISOK = "要保存设置吗?",
	NoSound = "静音。On Off"
}
