--[[
    GRF Editor [Version - 1.8.9.7]  [Build - 1.5.3.3063]
  
    This file was generated by GRF Editor
--______________________________________________________]]

-- Using GRF Editor Decompiler (beta 1.1.0)

SetupMSG = {
	Device = "使用硬体 T&L 加速弁遄COn Off f",
	Mode = "?定游?分辨率",
	FullScreen = "使用全屏幕。On Off",
	MouseExclusive = "?鼠?移??域?限于屏幕?。On Off",
	Sprite = "游??背景分辨率?整",
	Texture = "游???感分辨率?整",
	Bgm_Volume = "?整背景音?音量",
	Effect_Volume = "?整音效音量",
	bgm = "背景音?。ON OFF",
	sound = "音效。On Off",
	battlemode = "??Q ~ O 即可使用技能快捷列2的技能",
	notrade = "自?拒?交易申?。On Off",
	noshift = "不按Shift?以治愈?攻??人。On Off",
	noctrl = "不按Ctrl??自?攻?。On Off",
	skillfail = "不?示?字的使用技能失??息。On Off",
	notalkmsg = "聊天?容不?示于聊天?窗上。On Off",
	notalkmsg2 = "聊天?容不?示于聊天?窗上(含公??容)。 On Off",
	showname = "?更名??示方式",
	fog = "?或?FOG特效。On Off",
	aura = "?化极光。On Off",
	window = "移??窗位置?，?有吸附于其他?窗的?性。On Off",
	miss = "?示Miss。On Off",
	q1 = "用鼠?右??使用?存于F9的技能。On Off",
	q2 = "上、下??鼠????使用?存于F7和F8的技能。On Off",
	effect = "特效 On Off",
	loginout = "?示公???和好友的登?相??息。On Off",
	shopping = "??一次???商店，??商店名?右????商店。On Off",
	stateinfo = "?示有????示的?明。On Off",
	snap = "在攻??象附近引?鼠?游?。ON OFF",
	itemsnap = "在道具附近引?鼠?游?。ON OFF",
	skillsnap = "在技能施展的?象附近引?鼠?游?。ON OFF",
	hoai = "使用生命体的使用者人工智慧。ON OFF",
	merai = "使用佣兵的使用者人工智慧。 ON OFF",
	camera = "固定?角。ON OFF",
	lightmap = "在地?上?示?影部分。On Off",
	ISOK = "要?存?定??",
	NoSound = "?音。On Off"
}
