--[[
    GRF Editor [Version - 1.8.9.7]  [Build - 1.5.3.3063]
  
    This file was generated by GRF Editor
--______________________________________________________]]

-- Using GRF Editor Decompiler (beta 1.1.0)

SPUI_IDS = { SPU_CHAT = 0, SPU_FLOATING = 1, SPU_FLOATING_CHAT = 2 }
popuptbl = {
	[1] = {
		uitype = SPUI_IDS.SPU_CHAT,
		textcolor = 16763904,
		Description = {
			"此地区适用希罗斯里亚攻城战专用PVP规则。",
			"部分技能与道具的能力将会调整，或限制其功\能与使用。"
		}
	},
	[2] = {
		uitype = SPUI_IDS.SPU_FLOATING_CHAT,
		textcolor = 16763904,
		Description = {
			"此地区适用希罗斯里亚攻城战专用PVP规则。",
			"部分技能与道具的能力将会调整，或限制其功\能与使用。"
		}
	},
	[7] = {
		uitype = SPUI_IDS.SPU_FLOATING_CHAT,
		textcolor = 16763904,
		Description = {
			"已进入生物圈深层。",
			"禁止使用瞬间移动系技能及道具。",
			"禁止使用一部分移动相关技能。"
		}
	},
	[8] = {
		uitype = SPUI_IDS.SPU_FLOATING_CHAT,
		textcolor = 16763904,
		Description = {
			"已进入被遗忘的时间区域。",
			"禁止使用瞬间移动系列技能、道具。",
			"禁止部分移动相关技能。"
		}
	},
	[9] = {
		uitype = SPUI_IDS.SPU_FLOATING_CHAT,
		textcolor = 16763904,
		Description = { "已进入生物圈深层深渊。", "禁止使用瞬间移动系列技能或道具。" }
	}
}

-- Function #0
main = function()
	for ppID, PPDESC in pairs(popuptbl) do
		result, msg = AddMsg(ppID, PPDESC.uitype, PPDESC.textcolor)
		if not(result) then
			return false, msg
		end
		for k, v in pairs(PPDESC.Description) do
			result, msg = AddDesc(ppID, v)
			if not(result) then
				return false, msg
			end
		end
	end
	return true, "good"
end
