--[[
    GRF Editor [Version - 1.8.9.7]  [Build - 1.5.3.3063]
  
    This file was generated by GRF Editor
--______________________________________________________]]

-- Using GRF Editor Decompiler (beta 1.1.0)

SPUI_IDS = { SPU_CHAT = 0, SPU_FLOATING = 1, SPU_FLOATING_CHAT = 2 }
popuptbl = {
	[1] = {
		uitype = SPUI_IDS.SPU_CHAT,
		textcolor = 16763904,
		Description = {
			"此地區適用希羅斯里亞攻城戰專用PVP規則。",
			"部分技能與道具的能力將會調整，或限制其功\能與使用。"
		}
	},
	[2] = {
		uitype = SPUI_IDS.SPU_FLOATING_CHAT,
		textcolor = 16763904,
		Description = {
			"此地區適用希羅斯里亞攻城戰專用PVP規則。",
			"部分技能與道具的能力將會調整，或限制其功\能與使用。"
		}
	},
	[7] = {
		uitype = SPUI_IDS.SPU_FLOATING_CHAT,
		textcolor = 16763904,
		Description = {
			"已進入生物圈深層。",
			"禁止使用瞬間移動系技能及道具。",
			"禁止使用一部分移動相關技能。"
		}
	},
	[8] = {
		uitype = SPUI_IDS.SPU_FLOATING_CHAT,
		textcolor = 16763904,
		Description = {
			"已進入被遺忘的時間區域。",
			"禁止使用瞬間移動系列技能、道具。",
			"禁止部分移動相關技能。"
		}
	},
	[9] = {
		uitype = SPUI_IDS.SPU_FLOATING_CHAT,
		textcolor = 16763904,
		Description = { "已進入生物圈深層深淵。", "禁止使用瞬間移動系列技能或道具。" }
	}
}

-- Function #0
main = function()
	for ppID, PPDESC in pairs(popuptbl) do
		result, msg = AddMsg(ppID, PPDESC.uitype, PPDESC.textcolor)
		if not(result) then
			return false, msg
		end
		for k, v in pairs(PPDESC.Description) do
			result, msg = AddDesc(ppID, v)
			if not(result) then
				return false, msg
			end
		end
	end
	return true, "good"
end
