--[[
    GRF Editor [Version - 1.8.9.7]  [Build - 1.5.3.3063]
  
    This file was generated by GRF Editor
--______________________________________________________]]

-- Using GRF Editor Decompiler (beta 1.1.0)

Runetbl_desc = {
	[RUNETAGIDTBL.EPISODE17] = {
		[RUNEIDTBL.Rp_Ep17_Melee] = { Rune_DisplayName = "神秘零件(近距離)" },
		[RUNEIDTBL.Rp_Ep17_Range] = { Rune_DisplayName = "神秘零件(遠距離)" },
		[RUNEIDTBL.Rp_Ep17_Magic] = { Rune_DisplayName = "神秘零件(魔法)" },
		[RUNEIDTBL.Rp_Ep17_Razor] = { Rune_DisplayName = "神秘零件(暗器)" },
		[RUNEIDTBL.Rp_Ep17_Autoa] = { Rune_DisplayName = "全自動機甲A" },
		[RUNEIDTBL.Rp_Ep17_Autob] = { Rune_DisplayName = "全自動機甲B" },
		[RUNEIDTBL.Rp_Ep17_Bellare] = { Rune_DisplayName = "邪心獵人貝拉雷" },
		[RUNEIDTBL.Rp_Ep17_Sanare] = { Rune_DisplayName = "邪心獵人薩納雷" },
		[RUNEIDTBL.Rp_Ep17_Plaga] = { Rune_DisplayName = "普拉加" },
		[RUNEIDTBL.Rp_Ep17_Bestia] = { Rune_DisplayName = "貝斯帝亞" },
		[RUNEIDTBL.Rp_Ep17_Venenum] = { Rune_DisplayName = "貝納姆" },
		[RUNEIDTBL.Rp_Ep17_Dolor] = { Rune_DisplayName = "朵洛爾" },
		[RUNEIDTBL.Rp_Ep17_Iron] = { Rune_DisplayName = "廢鐵塊" },
		[RUNEIDTBL.Rp_Ep17_Redpepper] = { Rune_DisplayName = "火熱紅椒" },
		[RUNEIDTBL.Rp_Ep17_Addict] = { Rune_DisplayName = "魔力成癮者" },
		[RUNEIDTBL.Rp_Ep17_Caution] = { Rune_DisplayName = "魔力球體" },
		[RUNEIDTBL.Rp_Ep17_Withdraw] = { Rune_DisplayName = "魔力過載" },
		[RUNEIDTBL.Rp_Ep17_Bath] = { Rune_DisplayName = "三溫暖管理" },
		[RUNEIDTBL.Rp_Ep17_Papila] = { Rune_DisplayName = "帕皮拉三胞胎" },
		[RUNEIDTBL.Rp_Ep17_Book] = { Rune_DisplayName = "書呆子" },
		[RUNEIDTBL.Rp_Ep17_Garden] = { Rune_DisplayName = "庭園管理師" },
		[RUNEIDTBL.Rp_Ep17_Sewage] = { Rune_DisplayName = "下水道全明星" },
		[RUNEIDTBL.Rp_Ep17_Allergy] = { Rune_DisplayName = "小心過敏" },
		[RUNEIDTBL.Rp_Ep17_Fish] = { Rune_DisplayName = "熱(辣)湯" },
		[RUNEIDTBL.Rp_Ep17_Pitaya] = { Rune_DisplayName = "懶懶食人火龍果派對" },
		[RUNEIDTBL.Rp_Ep17_Tree] = { Rune_DisplayName = "庭園美化" },
		[RUNEIDTBL.Rp_Ep17_Aries] = { Rune_DisplayName = "艾里厄斯" },
		[RUNEIDTBL.Rp_Ep17_Machine] = { Rune_DisplayName = "故障的機器人" },
		[RUNEIDTBL.Rp_Ep17_Sweety] = { Rune_DisplayName = "斯威蒂" },
		[RUNEIDTBL.Rp_Ep17_Cat] = { Rune_DisplayName = "喵嗚" },
		[RUNEIDTBL.Rp_Ep17_Tiger] = { Rune_DisplayName = "老虎的氣息" }
	},
	[RUNETAGIDTBL.EVT] = {
		[RUNEIDTBL.Rp_21th_Poring] = { Rune_DisplayName = "夜市波利" },
		[RUNEIDTBL.Rp_21th_Lunatic] = { Rune_DisplayName = "夜市瘋兔" },
		[RUNEIDTBL.Rp_21th_Fabre] = { Rune_DisplayName = "夜市綠棉蟲" },
		[RUNEIDTBL.Rp_21th_Food] = { Rune_DisplayName = "夜市美食" }
	},
	[RUNETAGIDTBL.EPISODE18] = {
		[RUNEIDTBL.Rp_Ep18_Armor_A] = { Rune_DisplayName = "灰狼防具A" },
		[RUNEIDTBL.Rp_Ep18_Armor_B] = { Rune_DisplayName = "灰狼防具B" },
		[RUNEIDTBL.Rp_Ep18_Sword] = { Rune_DisplayName = "虛偽信念劍" },
		[RUNEIDTBL.Rp_Ep18_Spear] = { Rune_DisplayName = "虛偽信念重型武器" },
		[RUNEIDTBL.Rp_Ep18_Range] = { Rune_DisplayName = "虛偽信念遊俠" },
		[RUNEIDTBL.Rp_Ep18_Book] = { Rune_DisplayName = "虛偽信念書" },
		[RUNEIDTBL.Rp_Ep18_Magic] = { Rune_DisplayName = "虛偽信念魔法" },
		[RUNEIDTBL.Rp_Ep18_Fuuma] = { Rune_DisplayName = "虛偽信念刀刃" },
		[RUNEIDTBL.Rp_Ep18_Gun] = { Rune_DisplayName = "虛偽信念槍枝" },
		[RUNEIDTBL.Rp_Ep18_Katar] = { Rune_DisplayName = "虛偽信念拳套" },
		[RUNEIDTBL.Rp_Ep18_Instrum] = { Rune_DisplayName = "虛偽信念節奏" },
		[RUNEIDTBL.Rp_Ep18_Rakehand] = { Rune_DisplayName = "幽靈手耙" },
		[RUNEIDTBL.Rp_Ep18_Ashhopper] = { Rune_DisplayName = "灰塵波利製作法" },
		[RUNEIDTBL.Rp_Ep18_Phantom] = { Rune_DisplayName = "幽靈老鷹" },
		[RUNEIDTBL.Rp_Ep18_Greywolf] = { Rune_DisplayName = "灰狼" },
		[RUNEIDTBL.Rp_Ep18_Toad] = { Rune_DisplayName = "熔岩與灰燼" },
		[RUNEIDTBL.Rp_Ep18_Hot] = { Rune_DisplayName = "滾燙熔岩波利" },
		[RUNEIDTBL.Rp_Ep18_Burning] = { Rune_DisplayName = "火焰狼牙" },
		[RUNEIDTBL.Rp_Ep18_Demi] = { Rune_DisplayName = "半神" }
	},
	[RUNETAGIDTBL.EPISODE19] = {
		[RUNEIDTBL.Rp_Ep19_Armor_A] = { Rune_DisplayName = "雪花防具A" },
		[RUNEIDTBL.Rp_Ep19_Armor_B] = { Rune_DisplayName = "雪花防具B" },
		[RUNEIDTBL.Rp_Ep19_Sword] = { Rune_DisplayName = "冰晶劍" },
		[RUNEIDTBL.Rp_Ep19_Heavy] = { Rune_DisplayName = "冰晶粉碎者" },
		[RUNEIDTBL.Rp_Ep19_Edge] = { Rune_DisplayName = "冰晶鑿刻者" },
		[RUNEIDTBL.Rp_Ep19_Range] = { Rune_DisplayName = "冰晶穿刺者" },
		[RUNEIDTBL.Rp_Ep19_Magic] = { Rune_DisplayName = "冰晶詠唱者" },
		[RUNEIDTBL.Rp_Ep19_Gun] = { Rune_DisplayName = "冰晶射擊者" },
		[RUNEIDTBL.Rp_Ep19_Limacina] = { Rune_DisplayName = "青翅巨鳥" },
		[RUNEIDTBL.Rp_Ep19_Juncea] = { Rune_DisplayName = "融合" },
		[RUNEIDTBL.Rp_Ep19_Snow] = { Rune_DisplayName = "雪花" },
		[RUNEIDTBL.Rp_Ep19_Frozen] = { Rune_DisplayName = "冰凍湖水" },
		[RUNEIDTBL.Rp_Ep19_Dollo] = { Rune_DisplayName = "注視者" },
		[RUNEIDTBL.Rp_Ep19_Hallu] = { Rune_DisplayName = "家族" },
		[RUNEIDTBL.Rp_Ep19_Lesser] = { Rune_DisplayName = "失敗" },
		[RUNEIDTBL.Rp_Ep19_Middle] = { Rune_DisplayName = "潛入" },
		[RUNEIDTBL.Rp_Ep19_Upper] = { Rune_DisplayName = "改變" }
	}
}
