--[[
    GRF Editor [Version - 1.8.9.7]  [Build - 1.5.3.3063]
  
    This file was generated by GRF Editor
--______________________________________________________]]

-- Using GRF Editor Decompiler (beta 1.1.0)

OptionTbl = {
	[1] = {
		ID = TT_HIDE_AURA_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "오오라 표시",
		Tooltip = "/aura2",
		TipBoxID = 144,
		Default = true,
		Description = "오오라를 표시합니다.",
		MSGs = { "MSI_AURA_EFFECT_ON", "MSI_AURA_EFFECT_OFF" }
	},
	[2] = {
		ID = TT_FULL_AURA_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "오오라 표현",
		Tooltip = "/aura",
		TipBoxID = 144,
		Default = true,
		Description = "오오라를 간략하게 표현합니다.",
		MSGs = { "MSI_AURA_OFF", "MSI_AURA_ON" }
	},
	[3] = {
		ID = TT_EFFECT_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "이펙트 표시",
		Tooltip = "/effect",
		TipBoxID = 145,
		Default = true,
		Description = "스킬과 아이템의 이펙트를 표시합니다.",
		MSGs = { "MSI_EFFECT_ON", "MSI_EFFECT_OFF" }
	},
	[4] = {
		ID = TT_LIGHTMAP_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "음영 표시",
		Tooltip = "/lightmap",
		TipBoxID = 146,
		Default = true,
		Description = "음영을 표시합니다."
	},
	[5] = {
		ID = TT_EXTEND_DAMAGE_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "데미지 표기",
		TipBoxID = 88,
		Default = true,
		Description = "데미지를 확장 표기합니다."
	},
	[6] = {
		ID = TT_SHOW_MAP_NAME_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "맵 이름",
		TipBoxID = 69,
		Default = true,
		Description = "지역 이동 시, 맵 이름을 표시해줍니다."
	},
	[7] = {
		ID = TT_FOG_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "안개 이펙트",
		Tooltip = "/fog",
		TipBoxID = 147,
		Default = true,
		Description = "안개 효과를 표시합니다.",
		MSGs = { "MSI_GAME_SETTINGS_FOG_ON", "MSI_GAME_SETTINGS_FOG_OFF" }
	},
	[8] = {
		ID = TT_HIDE_FOOTPRINT_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "발자국 이펙트",
		TipBoxID = 148,
		Default = true,
		Description = "타인의 발자국 이펙트를 표시합니다."
	},
	[9] = {
		ID = TT_QUAKE_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "화면 흔들림",
		Tooltip = "/quake",
		TipBoxID = 149,
		Default = true,
		Description = "강력한 스킬 사용 시 화면이 흔들립니다.",
		MSGs = { "MSI_QUAKE_EFFECT_ON", "MSI_QUAKE_EFFECT_OFF" }
	},
	[10] = {
		ID = TT_HIDE_SUMMON_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "소환물 숨김",
		Tooltip = "",
		TipBoxID = 150,
		Default = false,
		Description = "소환물이 반투명으로 보입니다."
	},
	[11] = {
		ID = TT_HIDE_PLAYER_ON_OFF,
		Tab = EFFECT,
		Type = ONOFF,
		Title = "유저 숨김",
		Tooltip = "Ctrl + End",
		TipBoxID = 115,
		Default = false,
		Description = "타 유저가 반투명으로 보입니다.",
		MSGs = { "MSI_HIDE_PLAYER_ON", "MSI_HIDE_PLAYER_OFF" }
	},
	[12] = {
		ID = TT_ATTACK_SNAP_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "몬스터 스냅",
		Tooltip = "/snap",
		TipBoxID = 153,
		Default = false,
		Description = "몬스터 가까이 마우스를 대면 몬스터를 포착함.",
		MSGs = { "MSI_ATTACK_SNAP_ON", "MSI_ATTACK_SNAP_OFF" }
	},
	[13] = {
		ID = TT_SKILL_SNAP_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "스킬 스냅",
		Tooltip = "/skillsnap",
		TipBoxID = 153,
		Default = true,
		Description = "스킬 사용 시, 마우스가 근처 대상을 포착함.",
		MSGs = { "MSI_SKILL_SNAP_ON", "MSI_SKILL_SNAP_OFF" }
	},
	[14] = {
		ID = TT_ITEM_SNAP_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "아이템 스냅",
		Tooltip = "/itemsnap",
		TipBoxID = 153,
		Default = false,
		Description = "마우스가 바닥에 떨어진 가까운 아이템을 포착.",
		MSGs = { "MSI_ITEM_SNAP_ON", "MSI_ITEM_SNAP_OFF" }
	},
	[15] = {
		ID = TT_NOCTRL_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "No Ctrl",
		Tooltip = "/noctrl\n/nc",
		TipBoxID = 15,
		Default = true,
		Description = "Ctrl+클릭 하지 않아도 몬스터를 지속 공격함.",
		MSGs = { "MSI_NOCTRL_ON", "MSI_NOCTRL_OFF" }
	},
	[16] = {
		ID = TT_NOSHIFT_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "No Shift",
		Tooltip = "/noshift\n/ns",
		TipBoxID = 154,
		Default = false,
		Description = "회복 스킬로 몬스터 공격 시, Shift 누르지 않음.",
		MSGs = { "MSI_NOSHIFT_ON", "MSI_NOSHIFT_OFF" }
	},
	[17] = {
		ID = TT_EXPAND_SIGHT_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "Zoom Out",
		Tooltip = "/zoom",
		TipBoxID = 85,
		Default = true,
		Description = "줌 아웃 시, 화면이 조금 더 넓게 표시됨.",
		MSGs = { "MSI_EXPAND_SIGHT_ON", "MSI_EXPAND_SIGHT_OFF" }
	},
	[18] = {
		ID = TT_MOUSE_EXCLUSIVE_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "마우스 고정",
		TipBoxID = 155,
		Default = false,
		Description = "창 모드시, 마우스가 화면 밖으로 나가지 않음."
	},
	[19] = {
		ID = TT_QUICKSPELL_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "퀵스킬1",
		Tooltip = "/q1",
		TipBoxID = 156,
		Default = false,
		Description = "마우스 우버튼 클릭으로 F9키 스킬을 사용함.",
		MSGs = { "MSI_QUICKSPELL_ON", "MSI_QUICKSPELL_OFF" }
	},
	[20] = {
		ID = TT_QUICKSPELL2_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "퀵스킬2",
		Tooltip = "/q2",
		TipBoxID = 156,
		Default = false,
		Description = "마우스 휠로 F7, F8키 스킬을 사용함.",
		MSGs = { "MSI_QUICKSPELL2_ON", "MSI_QUICKSPELL2_OFF" }
	},
	[21] = {
		ID = TT_QUICK_SLOT_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "미니 슬롯",
		TipBoxID = 157,
		Default = true,
		Description = "2칸 짜리 미니 슬롯을 표시함."
	},
	[22] = {
		ID = TT_ITEM_COMPARE_ON_OFF,
		Tab = CONTROL,
		Type = ONOFF,
		Title = "장비 비교창",
		TipBoxID = 66,
		Default = true,
		Description = "장착한 장비와 비교하는 창을 표시함."
	},
	[23] = {
		ID = TT_NOTRADE_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/notrade",
		Tooltip = "/nt",
		TipBoxID = 167,
		Default = false,
		Description = "거래신청 및 친구신청을 자동으로 거절합니다.",
		MSGs = { "MSI_NOTRADE_ON", "MSI_NOTRADE_OFF" }
	},
	[24] = {
		ID = TT_NOTALKMSG_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/notalkmsg",
		Tooltip = "/nm",
		TipBoxID = 26,
		Default = false,
		Description = "채팅 내용을 채팅창에 표시하지 않습니다.",
		MSGs = { "MSI_NOTALKMSG_OFF", "MSI_NOTALKMSG_ON" }
	},
	[25] = {
		ID = TT_NOTALKMSG2_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/notalkmsg2",
		Tooltip = "/nm2",
		TipBoxID = 26,
		Default = false,
		Description = "길드말 포함 채팅 내용을 표시하지 않습니다.",
		MSGs = { "MSI_NOTALKMSG2_OFF", "MSI_NOTALKMSG2_ON" }
	},
	[26] = {
		ID = TT_BOLD_NAME_TYPE_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/showname",
		Tooltip = "/이름표시",
		TipBoxID = 168,
		Default = false,
		Description = "폰트가 얇아지고 길드명, 파티명을 표시합니다.",
		MSGs = { "MSI_SHOWNAME_ON", "MSI_SHOWNAME_OFF" }
	},
	[27] = {
		ID = TT_WINDOW_SNAP_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/window",
		Tooltip = "/wi",
		TipBoxID = 169,
		Default = true,
		Description = "창을 이동 시킬 때, 가까운 창과 잘 붙습니다.",
		MSGs = { "MSI_WINDOW_ON", "MSI_WINDOW_OFF" }
	},
	[28] = {
		ID = TT_MISS_EFFECT_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/miss",
		TipBoxID = 170,
		Default = true,
		Description = "공격 실패 시, miss가 표시됩니다.",
		MSGs = { "MSI_MISS_EFFECT_ON", "MSI_MISS_EFFECT_OFF" }
	},
	[29] = {
		ID = TT_SHOPPING_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/shopping",
		Tooltip = "/sh",
		TipBoxID = 171,
		Default = true,
		Description = "원클릭으로 상점을 열고, 우클릭으로 닫습니다.",
		MSGs = { "MSI_SHOPPING_ON", "MSI_SHOPPING_OFF" }
	},
	[30] = {
		ID = TT_STATEINFO_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/stateinfo",
		TipBoxID = 172,
		Default = true,
		Description = "상태 아이콘의 설명을 보여줍니다.",
		MSGs = { "MSI_SHOW_STATEINFO_ON", "MSI_SHOW_STATEINFO_OFF" }
	},
	[31] = {
		ID = TT_FIXED_CAMERA_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/camera",
		TipBoxID = 173,
		Default = false,
		Description = "화면 중심에 캐릭터를 고정합니다.",
		MSGs = { "MSI_FIXED_CAMERA_ON", "MSI_FIXED_CAMERA_OFF" }
	},
	[32] = {
		ID = TT_MONSTERHP_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/monsterhp",
		TipBoxID = 174,
		Default = true,
		Description = "공격한 몬스터의 HP가 표시됩니다.",
		MSGs = { "MSI_MONSTER_HP_ON", "MSI_MONSTER_HP_OFF" }
	},
	[33] = {
		ID = TT_SHOW_CASHSHOP_BTN_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/cashshop",
		TipBoxID = 175,
		Default = true,
		Description = "캐시샵 버튼을 표시합니다."
	},
	[34] = {
		ID = TT_SHOW_GOLDPCCAFE_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/goldpc",
		TipBoxID = 176,
		Default = true,
		Description = "골드PC방 마일리지를 표시합니다."
	},
	[35] = {
		ID = TT_SHOW_MINIMAP_BUTTON_ONOFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/minimap",
		TipBoxID = 177,
		Default = true,
		Description = "미니맵 하단 버튼을 표시합니다.",
		MSGs = { "MSI_MINIMAP_BUTTON_ON", "MSI_MINIMAP_BUTTON_OFF" }
	},
	[36] = {
		ID = TT_MIN_EFFECT_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/mineffect",
		TipBoxID = 145,
		Default = false,
		Description = "스킬 이펙트를 간략하게 표시합니다.",
		MSGs = { "MSI_MINEFFECT_ON", "MSI_MINEFFECT_OFF" }
	},
	[37] = {
		ID = TT_SPRITEMABLE_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/mable",
		TipBoxID = 178,
		Default = true,
		Description = "도람의 혼구슬을 표시합니다.",
		MSGs = { "MSI_SPRITEMABLE_ON", "MSI_SPRITEMABLE_OFF" }
	},
	[38] = {
		ID = TT_SHOW_EMBLEM_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/emblem",
		TipBoxID = 179,
		Default = true,
		Description = "엠블렘 이미지를 표시합니다.",
		MSGs = { "MSI_GAME_SETTINGS_EMBLEM_ON", "MSI_GAME_SETTINGS_EMBLEM_OFF" }
	},
	[39] = {
		ID = TT_NAME_ABOVE_HEAD_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/font",
		Tooltip = "/폰트",
		TipBoxID = 180,
		Default = false,
		Description = "캐릭터의 이름을 머리 위로 옮깁니다."
	},
	[40] = {
		ID = TT_BLOCK_CALL_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/call",
		Tooltip = "/호출",
		TipBoxID = 181,
		Default = true,
		Description = "호출 기능 스킬을 허용합니다."
	},
	[41] = {
		ID = TT_HOMUN_USERAI_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/hoai",
		Tooltip = "/호문지능",
		TipBoxID = 182,
		Default = false,
		Description = "호문클루스 AI를 커스터마이즈 합니다.",
		MSGs = { "MSI_HOMUN_USERAI_ON", "MSI_HOMUN_USERAI_OFF" }
	},
	[42] = {
		ID = TT_MER_USERAI_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/merai",
		TipBoxID = 182,
		Default = false,
		Description = "용병의 AI를 커스터마이즈 합니다.",
		MSGs = { "MSI_MER_USERAI_ON", "MSI_MER_USERAI_OFF" }
	},
	[43] = {
		ID = TT_SHOW_MERCHANT_SHOP_ON_OFF,
		Tab = ETC,
		Type = ONOFF,
		Title = "/showshop",
		Tooltip = "/노점보기",
		TipBoxID = 67,
		Default = true,
		Description = "노점을 표시합니다."
	},
	[44] = {
		ID = TT_EX_NO_COS_PLAY,
		Tab = ETC,
		Type = EXE,
		Title = "/nocosplay",
		Tooltip = "/환복\n/changedress",
		TipBoxID = 46,
		Description = "입고 있는 코스츔을 벗습니다."
	},
	[45] = {
		ID = TT_EX_HI,
		Tab = ETC,
		Type = EXE,
		Title = "/hi",
		TipBoxID = 183,
		Description = "친구로 등록된 캐릭터들에게 인사를 합니다."
	},
	[46] = {
		ID = TT_EX_HELP,
		Tab = ETC,
		Type = EXE,
		Title = "/h",
		TipBoxID = 2,
		Description = "명령어 일람."
	},
	[47] = {
		ID = TT_EX_SIT,
		Tab = ETC,
		Type = EXE,
		Title = "/sit",
		Tooltip = "/앉기\n/stand\n/서기\nInsert",
		TipBoxID = 184,
		Description = "서 있을 때 앉거나, 앉아 있을 때 섭니다."
	},
	[48] = {
		ID = TT_EX_EXIT_CHAT_ROOM,
		Tab = ETC,
		Type = EXE,
		Title = "/q",
		TipBoxID = 20,
		Description = "채팅방에서 나갑니다."
	},
	[49] = {
		ID = TT_EX_LEAVE_GROUP,
		Tab = ETC,
		Type = EXE,
		Title = "/leave",
		Tooltip = "/탈퇴",
		TipBoxID = 29,
		Description = "파티에서 나갑니다."
	},
	[50] = {
		ID = TT_EX_MAP_POS,
		Tab = ETC,
		Type = EXE,
		Title = "/where",
		Tooltip = "/좌표\n/장소",
		TipBoxID = 185,
		Description = "현재의 위치를 좌표를 포함하여 표시합니다."
	},
	[51] = {
		ID = TT_EX_REMEMBER_WARPPOINT,
		Tab = ETC,
		Type = EXE,
		Title = "/memo",
		Tooltip = "/기억",
		TipBoxID = 186,
		Description = "현재 장소를 워프저장장소로 기억합니다."
	},
	[52] = {
		ID = TT_EX_MAKE_CHAT_ROOM,
		Tab = ETC,
		Type = EXE,
		Title = "/chat",
		Tooltip = "/채팅방",
		TipBoxID = 20,
		Description = "채팅방 만들기창을 띄웁니다."
	},
	[53] = {
		ID = TT_EX_SAVE_CHAT,
		Tab = ETC,
		Type = EXE,
		Title = "/savechat",
		Tooltip = "/갈무리",
		TipBoxID = 24,
		Description = "채팅 내용을 파일로 저장합니다."
	},
	[54] = {
		ID = TT_EX_DORIDORI,
		Tab = ETC,
		Type = EXE,
		Title = "/doridori",
		TipBoxID = 187,
		Description = "캐릭터가 머리를 좌우로 흔듭니다."
	},
	[55] = {
		ID = TT_EX_BANGBANG,
		Tab = ETC,
		Type = EXE,
		Title = "/bangbang",
		TipBoxID = 188,
		Description = "캐릭터가 왼쪽 방향으로 돌아갑니다."
	},
	[56] = {
		ID = TT_EX_BINGBING,
		Tab = ETC,
		Type = EXE,
		Title = "/bingbing",
		TipBoxID = 189,
		Description = "캐릭터가 오른쪽 방향으로 돌아갑니다."
	},
	[57] = {
		ID = TT_EX_WHISPER_BLOCK_LIST,
		Tab = ETC,
		Type = EXE,
		Title = "/ex",
		TipBoxID = 28,
		Description = "귓말 차단한 캐릭터 리스트를 보여줍니다."
	},
	[58] = {
		ID = TT_EX_WHISPER_ALL_ACCEPT,
		Tab = ETC,
		Type = EXE,
		Title = "/inall",
		TipBoxID = 28,
		Description = "모두에게 귓말 가능 상태가 됩니다."
	},
	[59] = {
		ID = TT_EX_WHISPER_ALL_BLOCK,
		Tab = ETC,
		Type = EXE,
		Title = "/exall",
		TipBoxID = 28,
		Description = "모두에게 귓말 거부 상태가 됩니다."
	},
	[60] = {
		ID = TT_EX_RANK_BLACKSMITH,
		Tab = ETC,
		Type = EXE,
		Title = "/blacksmith",
		TipBoxID = 190,
		Description = "블랙스미스의 상위 10위권 랭킹을 보여줍니다."
	},
	[61] = {
		ID = TT_EX_RANK_ALCHEMIST,
		Tab = ETC,
		Type = EXE,
		Title = "/alchemist",
		TipBoxID = 190,
		Description = "알케미스트의 상위 10위권 랭킹을 보여줍니다."
	},
	[62] = {
		ID = TT_EX_RANK_TAEKWON,
		Tab = ETC,
		Type = EXE,
		Title = "/taekwon",
		TipBoxID = 193,
		Description = "태권 상위 10위권 랭킹을 보여줍니다."
	}
}
